JOBS_DISABLE_TIME: '0'
COPY_COST: '0'
WAND: 'NETHER_STAR'
ADMIN_PERMISSION: 'minecraft.admin'
DEFAULT_MAX_THREAD: '2'
DEFAULT_USE_THREAD: '2'
ALLOW_WORLD_NAME: 'world'
BLOCK_PLACE_COOLDOWN: '50'
DISABLE_BLOCKS:
  - 'BARRIER'
REPLACEABLE_BLOCKS:
  - 'AIR'
NON_CONSUMABLE_BLOCKS:
  - 'AIR'
  - 'WATER'