name: AutoFill
version: '${project.version}'
main: org.minecraft.autofill.Autofill
api-version: 1.20
softdepend: [WorldGuard, CoreProtect, mcMMO, Jobs]
commands:
  autofill:
    description: AutoFill Command
    permission: autofill.command
    permission-message: Permission denied
    aliases: af